### ISSUE TITLE
Displayed Reasoning changes upstream

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/cubical-categorical-logic#110]
I just merged [this PR](https://github.com/agda/cubical/pull/1153) upstream, which should help us out but means basically all proofs using the displayed reasoning module need to be updated. Somebody should take care of that. Make sure to build on https://github.com/maxsnew/cubical-categorical-logic/pull/107 which addresses some earlier upstream changes.

**Comment by hejohns** [comment]
working in #111

**Comment by hejohns** [comment]
closing with #111
