### ISSUE TITLE
CI is Broken

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/cubical-categorical-logic#113]
@stschaef getting errors building *Agda* in the CI, ugh

**Comment by stschaef** [comment]
Whack. I'll prioritize this and the grammars CI work for the rest of the morning

**Comment by maxsnew** [comment]
well since CI is broken anyway I'll just merge that PR now without waiting for CI to be fixed

**Comment by stschaef** [comment]
https://github.com/agda/cubical/issues/1161

Even the Cubical CI fails for me in a clean fork of the repo. Seems like a dependency change for Agda, going to test an install on a clean ubuntu VM and then open an issue on the Agda repo if the issue persists

**Comment by maxsnew** [comment]
Fixed upstream
