### ISSUE TITLE
Adjoints

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/cubical-categorical-logic#18]
Once https://github.com/maxsnew/multi-poly-cats/issues/7 is done, there are several applications to adjunctions that are more or less immediate:
1. In `Cubical.Categories.Adjoint` They give two definitions of adjoint functors (unit/counit and hom-bijection) and construct functions back and forth between them (no proof of Iso). The hom-bijection one should be fairly easy to show is Iso to a formulation using profunctors because it essentially is in terms of profunctors.
2. Then we can define the "universal element" definitions of left and right adjoints (i.e., given one functor F a right adjoint a functor representing Hom(F-,=). And it should follow by stuff we already have that this is Iso to the hom-bijection definition.
3. I think actually proving the iso between unit/counit and hom-bijection doesn't directly follow from what we've done so far but we should be able to reuse most of the functions we have right? Maybe there's a variant of the Yoneda lemma we can extract that is the kernel of the argument?

**Comment by maxsnew** [comment]
But we probably shouldn't bother with (3) before the pr. I've already done (2) so (1) is all that's left

**Comment by GenericMonkey** [comment]
Regarding 1 -- when you say "is Iso to a formulation using profunctors" -- is this the definition in `Categories/Adjoint/UniversalElements.agda`? I also found [this definition](https://ncatlab.org/nlab/show/adjoint+functor#InTermsOfCographsHeteromorphisms) on nlab -- is this a good place to wrap my head around the definition there?

**Comment by maxsnew** [comment]
Removing this from the milestone as we don't really need it for anything, we just use the formulation of adjoints in terms of representables
