### ISSUE TITLE
Wide Subcategories

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/cubical-categorical-logic#54]
We defined [full subcategories](https://github.com/maxsnew/multi-poly-cats/blob/new-profunctors/Cubical/Categories/Displayed/Constructions/FullSubcategory.agda) as displayed categories in the new PR, it would be nice to have the opposite extreme, a ["wide" subcategory](https://ncatlab.org/nlab/show/wide+subcategory) as well.

**Comment by maxsnew** [comment]
Naming update: `FullSubcategory` has been merged upstream and is now called `PropertyOver`. I guess that means `WideSubcategory` should be like `HomPropertyOver` or something

**Comment by stschaef** [comment]
See #100
