### ISSUE TITLE
Properties of SETᴰ

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/cubical-categorical-logic#62]
Prove that SETᴰ aka the families fibration is
1. a fibration
2. has fibered terminal objects
3. has fibered binary cartesian products

**Comment by hejohns** [comment]
closing, see https://github.com/maxsnew/cubical-categorical-logic/pull/74#issuecomment-2193687010

**Comment by hejohns** [comment]
Reopening, since this shouldn't be closed until #94 is actually merged
