### ISSUE TITLE
Recursor for free cartesian categories

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/cubical-categorical-logic#75]
This should be implemented using the eliminator, we just need to show that if `C` and `D` are cartesian categories then `weaken C D` is a displayed cartesian category.

**Comment by hejohns** [comment]
Should be closed by #94, once merged

https://github.com/maxsnew/cubical-categorical-logic/blob/9f3919dd02b8c3b53650e99cbcaaed48b38fe583/Cubical/Categories/Constructions/Free/CartesianCategory/Base.agda#L221

https://github.com/maxsnew/cubical-categorical-logic/blob/9f3919dd02b8c3b53650e99cbcaaed48b38fe583/Cubical/Categories/Displayed/Constructions/Weaken/Properties.agda#L42
