### ISSUE TITLE
Cartesian Closed Structure on Presheaf Category

### ISSUE THREAD

**Issue by bond15** [maxsnew/cubical-categorical-logic#97]
(Max, feel free to delete/rewrite this issue)

So far, product of presheaves exists [here](https://github.com/maxsnew/cubical-categorical-logic/blob/018eb366af6ca889316fb76de3448a0c669d4169/Cubical/Categories/Presheaf/Constructions.agda).

I've put in a fair amount of work on this [here](https://github.com/bond15/Bunched-CBPV/blob/main/cruft/LearnPresheaf.agda), but this is a massive hack and not usable.

**Comment by bond15** [comment]
https://github.com/maxsnew/cubical-categorical-logic/tree/Presheaf-CCC
started work here

**Comment by maxsnew** [comment]
Would also be nice to have that presheaf categories are complete.

**Comment by bond15** [comment]
Using something like this? 
https://github.com/agda/cubical/blob/6d6870cbf537294fc3fdf9c5a34909bde30ba914/Cubical/Categories/Limits/Limits.agda#L349

I finished the cartesian closed structure, almost ready for review.. still cleaning things up.

**Comment by bond15** [comment]
This was merged in https://github.com/maxsnew/cubical-categorical-logic/pull/102

**Comment by bond15** [comment]
This was [completed](https://github.com/maxsnew/cubical-categorical-logic/pull/102)

**Comment by bond15** [comment]
This was [completed](https://github.com/maxsnew/cubical-categorical-logic/pull/102)
